-- Mind Model overview insight (§4a): an LLM-written synthesis of the other four
-- kinds, generated by a live Anthropic API call. Additive only, following the
-- DROP CONSTRAINT / ADD CONSTRAINT pattern 003_inbox.sql used for notes.para.
-- NOT VALID because the runner replays every file: once 006 widens this list and
-- cycles write user_model/recommendation rows, re-validating 005's narrower set
-- against existing data fails. NOT VALID still enforces the check for new rows at
-- this point in a fresh install, and 006 replaces it with the final list anyway.
ALTER TABLE mind_insights DROP CONSTRAINT IF EXISTS mind_insights_kind_check;
ALTER TABLE mind_insights ADD CONSTRAINT mind_insights_kind_check
  CHECK (kind IN ('interest_cluster', 'open_loop', 'attention_pattern', 'dormant_revival', 'inferred_goal', 'overview')) NOT VALID;
