-- Mind Model overview insight (§4a): an LLM-written synthesis of the other four
-- kinds, generated by a live Anthropic API call. Additive only, following the
-- DROP CONSTRAINT / ADD CONSTRAINT pattern 003_inbox.sql used for notes.para.
ALTER TABLE mind_insights DROP CONSTRAINT IF EXISTS mind_insights_kind_check;
ALTER TABLE mind_insights ADD CONSTRAINT mind_insights_kind_check
  CHECK (kind IN ('interest_cluster', 'open_loop', 'attention_pattern', 'dormant_revival', 'inferred_goal', 'overview'));
